name: CI Pipeline
run-name: ${{ github.actor }} is deploying Random Picker 🎲
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  Build_and_Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4.2.2

      - name: Setup Node/NPM
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 22

      - name: Build
        run: |
          npm install
          CI=false npm run build

      - name: CDK diff
        uses: sightsoundtheatres/aws-cdk-github-actions@cfadb4843373e20d1c23d5f702e62a7a1b736b5a
        with:
          cdk_subcommand: 'diff'
          working_dir: './infrastructure'
          actions_comment: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'

      - name: CDK deploy
        uses: sightsoundtheatres/aws-cdk-github-actions@cfadb4843373e20d1c23d5f702e62a7a1b736b5a
        with:
          cdk_subcommand: 'deploy'
          working_dir: './infrastructure'
          cdk_stack: 'RandomPickerInfrastructureStack'
          cdk_args: '--require-approval never'
          actions_comment: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
